@startuml DS1_Autenticacao
skinparam sequenceMessageAlign center
skinparam responseMessageBelowArrow true
skinparam maxMessageSize 200
skinparam sequenceArrowThickness 1.2
skinparam roundcorner 6
skinparam sequenceParticipantBorderColor #534AB7
skinparam sequenceParticipantBackgroundColor #EEEDFE
skinparam sequenceActorBorderColor #534AB7
skinparam sequenceActorBackgroundColor #EEEDFE
skinparam sequenceLifeLineBorderColor #AFA9EC
skinparam sequenceGroupBackgroundColor #F8F8FF
skinparam sequenceGroupBorderColor #AFA9EC
skinparam noteBorderColor #EF9F27
skinparam noteBackgroundColor #FAEEDA

title DS1 — Autenticação e Controlo de Sessão (RF1, RF2)

actor "Utilizador" as U
participant "AutenticacaoController" as AC <<Apresentação>>
participant "IAutenticacaoServico" as AS <<Serviço>>
participant "UtilizadorRepositorio" as UR <<Repositório>>
participant "ConfiguracaoTerminal" as CT <<Configuração>>

== Arranque da aplicação ==

AC -> CT : getIdLoja()
activate CT
CT --> AC : idLoja
deactivate CT
note right of CT
  Lida do ficheiro de configuração
  local no arranque (ADR-02, RF2).
  Não alterável pela interface.
end note

== Submissão de credenciais ==

U -> AC : onLoginSubmit(nomeUtilizador, palavraPasse)
activate AC

AC -> AS : autenticar(nomeUtilizador, palavraPasse)
activate AS

AS -> UR : buscarPorCredenciais(nomeUtilizador, hashPalavraPasse)
activate UR

alt credenciais inválidas
  UR --> AS : null
  AS --> AC : <<lança>> CredenciaisInvalidasException
  AC --> U : alerta — "Credenciais inválidas"
else credenciais válidas
  UR --> AS : utilizador : Utilizador
  deactivate UR

  == Validação da sessão duplicada (RF1) ==

  AS -> UR : verificarSessaoAtiva(utilizador.getId())
  activate UR
  UR --> AS : emSessao : boolean
  deactivate UR

  alt emSessao = true
    AS --> AC : <<lança>> SessaoDuplicadaException
    AC --> U : alerta — "Utilizador já autenticado\nnoutro terminal"
  else emSessao = false

    note over AS
      Marca utilizador como em sessão
      actualizando o campo emSessao = true
      na base de dados local (RF1).
    end note

    AS -> UR : atualizar(utilizador)
    activate UR
    UR --> AS : ok
    deactivate UR

    AS --> AC : utilizador : Utilizador
    deactivate AS

    AC --> U : navegar para ecrã principal\n(funcionalidades conforme perfil)

  end
end

deactivate AC

== Encerramento de sessão ==

U -> AC : onLogout()
activate AC
AC -> AS : encerrarSessao(utilizador)
activate AS

note over AS
  Marca utilizador como fora de sessão
  actualizando o campo emSessao = false.
end note

AS -> UR : atualizar(utilizador)
activate UR
UR --> AS : ok
deactivate UR
AS --> AC : ok
deactivate AS
AC --> U : ecrã de login
deactivate AC

@enduml
