@startuml
left to right direction


actor Manager as M
actor CEO as C

C --|> M

rectangle "Software de Loja - Gestão Administrativa" {
  M -- (Gerir Utilizadores do Sistema)
  M -- (Realizar Fecho de Dia)
}

note bottom of (Gerir Utilizadores do Sistema)
  Manager gere Funcionários da sua loja
  CEO gere Manager da loja onde está autenticado
end note
@enduml
