@startuml
left to right direction
actor Funcionário
actor Manager
actor CEO

Manager --|> Funcionário
CEO --|> Manager

rectangle "Software de Loja - Operação Diária" {
  Funcionário -- (Iniciar Sessão no Terminal da Loja)
  Funcionário -- (Registar Venda)
  Funcionário -- (Registar Devolução)
  Funcionário -- (Consultar e Pesquisar Produtos)
  Funcionário -- (Monitorizar Caixa e Registar Sangria)
}
@enduml
