@startuml servidor_central_servicos_autenticacao_recepcao
skinparam classAttributeIconSize 0
skinparam classFontSize 12
skinparam classHeaderBackgroundColor #E1F5EE
skinparam classBorderColor #0F6E56
skinparam classBackgroundColor #FAFAFA
skinparam arrowColor #0F6E56
skinparam stereotypeCBackgroundColor #EEEDFE
skinparam stereotypeABackgroundColor #FAC775
skinparam stereotypeIBackgroundColor #D1ECF1
skinparam packageBackgroundColor #F8F8F8
skinparam packageBorderColor #B4B2A9
skinparam linetype ortho
skinparam nodesep 40
skinparam ranksep 50

title Servidor Central — Serviços (Autenticação e Receção)

package "Serviço (Interfaces - Autenticação e Receção)" #E0F0E0 {

  interface IAutenticacaoCentralServico {
    + autenticar(nomeUtilizador : String, palavraPasse : String) : CEO
    + registarTentativaFalhada(nomeUtilizador : String) : void
  }

  interface IRecepcaoPacoteServico {
    + receberPacote(dto : PacoteFechoDTO) : boolean
    + validarIntegridade(dto : PacoteFechoDTO) : boolean
  }
}

package "Serviço (Implementações - Autenticação e Receção)" #EEF9F4 {

  class AutenticacaoCentralServico {
    - ceoRepositorio : CEORepositorio
    + autenticar(nomeUtilizador : String, palavraPasse : String) : CEO
    + registarTentativaFalhada(nomeUtilizador : String) : void
    - estaBloqueada(ceo : CEO) : boolean
    - desbloquearSeExpirado(ceo : CEO) : void
  }

  class RecepcaoPacoteServico {
    - lojaRepositorio : LojaRepositorio
    - vendaRepositorio : VendaCentralRepositorio
    - devolucaoRepositorio : DevolucaoCentralRepositorio
    - remessaRepositorio : RemessaCentralRepositorio
    - pagamentoRepositorio : PagamentoCentralRepositorio
    - sessaoCaixaRepositorio : SessaoCaixaCentralRepositorio
    - logRepositorio : LogAuditoriaCentralRepositorio
    - fechoDiaCentralRepositorio : FechoDiaCentralRepositorio
    + receberPacote(dto : PacoteFechoDTO) : boolean
    + validarIntegridade(dto : PacoteFechoDTO) : boolean
    - persistirEntidades(dto : PacoteFechoDTO, loja : Loja) : void
  }
}

' Implementações realizam interfaces
AutenticacaoCentralServico ..|> IAutenticacaoCentralServico
RecepcaoPacoteServico ..|> IRecepcaoPacoteServico

' Serviços → Repositórios
AutenticacaoCentralServico ..> CEORepositorio
RecepcaoPacoteServico ..> LojaRepositorio
RecepcaoPacoteServico ..> VendaCentralRepositorio
RecepcaoPacoteServico ..> DevolucaoCentralRepositorio
RecepcaoPacoteServico ..> RemessaCentralRepositorio
RecepcaoPacoteServico ..> PagamentoCentralRepositorio
RecepcaoPacoteServico ..> SessaoCaixaCentralRepositorio
RecepcaoPacoteServico ..> LogAuditoriaCentralRepositorio
RecepcaoPacoteServico ..> FechoDiaCentralRepositorio

@enduml
