@startuml servicos_gestao
skinparam classAttributeIconSize 0
skinparam classFontSize 12
skinparam classHeaderBackgroundColor #EEEDFE
skinparam classBorderColor #534AB7
skinparam classBackgroundColor #FAFAFA
skinparam arrowColor #534AB7
skinparam stereotypeCBackgroundColor #E1F5EE
skinparam stereotypeABackgroundColor #FAC775
skinparam stereotypeIBackgroundColor #D1ECF1
skinparam packageBackgroundColor #F8F8F8
skinparam packageBorderColor #B4B2A9
skinparam linetype ortho
skinparam nodesep 40
skinparam ranksep 50

title Software de Loja — Serviços de Gestão

' ╔══════════════════════════════════════╗
' ║          CAMADA DE SERVIÇO           ║
' ║       (Serviços de Gestão)           ║
' ╚══════════════════════════════════════╝
package "Serviço (Serviços de Gestão)" #EEF9F4 {

  class RemessaServico {
    - remessaRepositorio : RemessaRepositorio
    - pedidoRemessaRepositorio : PedidoRemessaRepositorio
    - catalogoServico : CatalogoServico
    - pagamentoServico : PagamentoServico
    - auditoriaServico : AuditoriaServico
    - autorizacaoServico : AutorizacaoServico
    + registarRemessa(utilizador : Utilizador, fornecedor : Fornecedor, linhas : List~LinhaRemessa~, valorTotalGuia : double) : Remessa
    + associarPedidoPendente(remessa : Remessa) : void
    + criarPedidoRemessa(utilizador : Utilizador, fornecedor : Fornecedor, linhas : List~LinhaPedidoRemessa~) : PedidoRemessa
    + listarPedidos(estado : EstadoPedido) : List~PedidoRemessa~
  }

  class PagamentoServico {
    - pagamentoRepositorio : PagamentoRepositorio
    - auditoriaServico : AuditoriaServico
    - autorizacaoServico : AutorizacaoServico
    + listarPendentes() : List~Pagamento~
    + liquidar(idPagamento : int, utilizador : Utilizador) : void
  }

  class UtilizadorServico {
    - utilizadorRepositorio : UtilizadorRepositorio
    - auditoriaServico : AuditoriaServico
    - autorizacaoServico : AutorizacaoServico
    + criar(gestor : Utilizador, dados : UtilizadorDTO) : Utilizador
    + desativar(gestor : Utilizador, idAlvo : int) : void
    + editar(gestor : Utilizador, idAlvo : int, dados : UtilizadorDTO) : void
    + validarGestorAtivo(idLoja : String) : void
  }
}

' Relações com Repositórios
RemessaServico ..> RemessaRepositorio
RemessaServico ..> PedidoRemessaRepositorio
PagamentoServico ..> PagamentoRepositorio
UtilizadorServico ..> UtilizadorRepositorio

' Comunicação Lateral
RemessaServico ..> CatalogoServico : " atualiza stock"
RemessaServico ..> PagamentoServico : " agenda pagamento"

' Serviços transversais e Segurança
RemessaServico ..> AutorizacaoServico
PagamentoServico ..> AutorizacaoServico
UtilizadorServico ..> AutorizacaoServico

RemessaServico ..> AuditoriaServico
PagamentoServico ..> AuditoriaServico
UtilizadorServico ..> AuditoriaServico

@enduml
