loja.id=LOJA_001
loja.nome=Loja de Conveniência TrasmUM
loja.limiteMaximoCaixa=500.00
servidor.url=https://localhost:8443
servidor.alertaValidade.dias=7
servidor.truststore.path=
servidor.truststore.password=

db.url=jdbc:mysql://localhost:3306/trasmum_loja?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
db.user=trasmum
db.password=trasmum
