@startuml
left to right direction

actor Funcionário as F
actor Manager as M
actor CEO as C

M --|> F
C --|> M

rectangle "Software de Loja" {
  F -- (Iniciar Sessão no Terminal da Loja)
  F -- (Registar Venda)
  F -- (Registar Devolução)
  F -- (Consultar e Pesquisar Produtos)
  F -- (Monitorizar Caixa e Registar Sangria)

  M -- (Criar Pedidos de Remessa)
  M -- (Registar Receção de Remessa)
  M -- (Gerir Catálogo de Produtos)
  M -- (Gerir Documentos de Fornecedores)
  M -- (Gerir Pagamentos a Fornecedores)
  M -- (Aplicar Desconto por Prazo de Validade)
    M -- (Gerir Utilizadores do Sistema)
  M -- (Realizar Fecho de Dia)
}

rectangle "Software de Servidor Central" {
  C -- (Iniciar Sessão no Servidor Central)
  C -- (Consultar Estado de Consolidação de Rede)
  C -- (Consultar Remessas da Rede)
  C -- (Consultar Dashboards e Relatórios Analíticos)
}
@enduml
